# Generated by Django 5.1.15 on 2026-07-05 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0002_pipelinerun_retry_count_pipelinerun_traceback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineWatermark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(blank=True, max_length=200)),
                (
                    "pipeline",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watermark",
                        to="pipelines.pipeline",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
