# Generated by Django 5.1.15 on 2026-07-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0003_pipelinewatermark"),
        ("workspaces", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipelines",
                to="workspaces.workspace",
            ),
        ),
    ]
