# Generated by Django 5.1.15 on 2026-07-05 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasources", "0001_initial"),
        ("pipelines", "0002_pipelinerun_retry_count_pipelinerun_traceback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LineageNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("SOURCE", "Source"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "data_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineage_nodes",
                        to="datasources.datasource",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineage_nodes",
                        to="metadata.dataset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineageEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("column_mapping", models.JSONField(blank=True, default=list)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineage_edges",
                        to="pipelines.pipeline",
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="metadata.lineagenode",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="metadata.lineagenode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchemaVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("columns", models.JSONField()),
                ("added_columns", models.JSONField(blank=True, default=list)),
                ("removed_columns", models.JSONField(blank=True, default=list)),
                ("renamed_columns", models.JSONField(blank=True, default=list)),
                ("is_drift", models.BooleanField(default=False)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_versions",
                        to="metadata.dataset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schema_versions",
                        to="pipelines.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ColumnMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("dtype", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns_meta",
                        to="metadata.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "name"), name="unique_dataset_column"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="lineagenode",
            constraint=models.UniqueConstraint(
                fields=("layer", "name"), name="unique_lineage_node"
            ),
        ),
        migrations.AddConstraint(
            model_name="lineageedge",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "from_node", "to_node"),
                name="unique_pipeline_lineage_edge",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemaversion",
            constraint=models.UniqueConstraint(
                fields=("dataset", "version"), name="unique_dataset_schema_version"
            ),
        ),
    ]
