# Generated by Django 5.1.15 on 2026-07-06 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0001_initial"),
        ("pipelines", "0004_pipeline_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnAnomaly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("column", models.CharField(max_length=200)),
                ("value", models.FloatField()),
                ("baseline_mean", models.FloatField()),
                ("baseline_stddev", models.FloatField()),
                ("z_score", models.FloatField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="metadata.dataset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomalies",
                        to="pipelines.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ColumnStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("column", models.CharField(max_length=200)),
                ("count", models.PositiveIntegerField(default=0)),
                ("mean", models.FloatField(default=0.0)),
                ("m2", models.FloatField(default=0.0)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_stats",
                        to="metadata.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["column"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "column"), name="unique_dataset_column_stats"
                    )
                ],
            },
        ),
    ]
