# Generated by Django 5.1.15 on 2026-07-06 09:35

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0001_initial"),
        ("workspaces", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_sources",
                to="workspaces.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="config",
            field=apps.common.fields.EncryptedJSONField(blank=True, default=dict),
        ),
    ]
