# Generated by Django 5.1.15 on 2026-07-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasources", "0002_datasource_workspace_alter_datasource_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("FILE", "File"),
                    ("POSTGRES", "Postgres"),
                    ("REST_API", "REST API"),
                    ("S3", "S3 (or compatible)"),
                ],
                max_length=16,
            ),
        ),
    ]
