# Generated by Django 5.1.15 on 2026-07-05 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipelines", "0002_pipelinerun_retry_count_pipelinerun_traceback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityScorecard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completeness", models.FloatField()),
                ("consistency", models.FloatField()),
                ("accuracy", models.FloatField()),
                ("overall_score", models.FloatField()),
                ("passed", models.BooleanField()),
                ("checks", models.JSONField(blank=True, default=list)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecard",
                        to="pipelines.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
