# Generated by Django 5.1.15 on 2026-07-05 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("signup_date", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
