# Generated by Django 5.1.15 on 2026-07-05 09:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipelines", "0002_pipelinerun_retry_count_pipelinerun_traceback_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("RUN_FAILED", "Run failed"),
                            ("RUN_SUCCEEDED", "Run succeeded"),
                            ("RUN_RETRYING", "Run retrying"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("SLACK", "Slack")], max_length=10
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=255)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="pipelines.pipelinerun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("slack_enabled", models.BooleanField(default=False)),
                (
                    "slack_webhook_url",
                    models.URLField(
                        blank=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="slack_webhook_url must be a real Slack webhook URL (https://hooks.slack.com/services/...)",
                                regex="^https://hooks\\.slack\\.com/services/.+",
                            )
                        ],
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
